# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
  repositories:
  - repository: AzureTests # The name used to reference this repository in the checkout step
    type: github
    endpoint: GitHub-CUCraigT
    name: C2-Labs/atlas_tests

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    pwd
    ls
    cd atlas-deploy
    pwd
    ls
  displayName: 'Run a multi-line script in Self Repo'

- script: |
    pwd
    ls
  displayName: 'Run a multi-line script in Self Repo'

- checkout: AzureTests

- script: |
    cd atlas_tests
    ls
    pwd
  displayName: 'Run a multi-line script in AzureTests'

- task: Maven@3
  continueOnError: true
  inputs:
    mavenPomFile: 'atlas_tests/pom.xml'
    options: '-Durl="https://atlas-dev.c2labs.com"'
    publishJUnitResults: true
    testResultsFiles: 'atlas_tests/**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: PublishCucumberReport@1
  continueOnError: true
  inputs:
    jsonDir: 'atlas_tests/target'
    outputPath: '.las_tests/target'
    theme: 'bootstrap'
    reportSuiteAsScenarios: true
    name: 'ATLAS Functional Testing'
    title: 'ATLAS Cucumber Tests'
