apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlas
  namespace: atlas
spec:
  selector:
    matchLabels: 
      app: atlas
  replicas: 1
  template:
    metadata:
      labels:
        app: atlas
    spec:
      containers:
      - name: atlas
        image: c2labs/atlas-c2internal:0.1.0-beta
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: "/atlas/files"
            name: atlas-files 
        envFrom:
        - configMapRef:
            name: atlas-config
        - secretRef:
            name: atlas-secrets
      volumes:
      - name: atlas-files
        persistentVolumeClaim:
          claimName: atlas-files