version: '3.7'

services:
  atlas-db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    hostname: atlas-db
    networks:
      - atlas_net
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    env_file:
      - db.env

  atlas:
    image: c2labs/atlas-c2internal:0.5.0-beta
    hostname: atlas
    depends_on:
      - atlas-db
    networks:
      - atlas_net
    ports:
      - "81:80"
    volumes:
      - atlasvolume:/atlas/files
    env_file:
      - atlas.env
    entrypoint:
      - ./wait-for-it.sh
      - atlas-db:1433
      - --timeout=90
      - --strict
      - --
      - ./Atlas

networks:
  atlas_net:
    driver: bridge
volumes:
  sqlvolume:
  atlasvolume: